### PR TITLE
FIX: exit debugger thread when main thread exits

### PR DESCRIPTION
**Pull request by kzidane**

### CODE REVIEW

**Comment by kzidane** [comment]
@cmorisse thoughts on this?

**Comment by cmorisse** [comment]
Sorry for the late answer; I'm busy at this time.
I've seen all your "interactions" on github and I'm really happy about them. Thanks for that.

About to this PR, it's ok for me, but I'm not working on a python 3 project at that time and I'm not able to test extensively.
So I will create a next_release branch and merge into it.

You may know it, but there are 2 debuggers (ikpdb python 2 and ikp3db python 3). I rewrote  ikp3db as I wanted a pure python 3. But today I maintain both. 
So if you have an idea for the python 2 version I'm really interested in.

Thanks again

**Comment by cmorisse** [comment]
Thanks you so much !

**Comment by cmorisse** [comment]
Finally, I won't keep this one.
The problem is that sometimes the command loop hangs/returns an error because it receives some data while the main thread is already terminated.
I think the solution is to modify the command loop to manage a timeout,  then periodically wether main thread is terminated to quit.

**Pull request merged**
